name: ripple-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - python=3.10.9
  - pip
  - pip:
    - glob2==0.7
    - h5py==3.8.0
    - mat73==0.60
    - mne==1.6.0
    - moviepy==1.0.3
    - multiprocess==0.70.14
    - neo==0.12.0
    - pandas
    - scipy
    - seaborn
    - statsmodels==0.13.5
    - tqdm
