name: ripple-detection
channels:
  - pennmem
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cffi=1.15.1
  - contourpy=1.0.5
  - cryptography=41.0.2
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.8
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - jedi=0.18.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=12.3.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - matplotlib
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pillow=9.4.0
  - ply=3.11
  - psutil=5.9.0
  - ptsa=3.0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-global=2.10.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.2.0
  - swig=4.0.2
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - traits=6.2.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - xarray=2023.6.0
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip
  - pip:
    - bs4==0.0.1
    - charset-normalizer==3.1.0
    - comm==0.2.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dill==0.3.6
    - fonttools==4.25.0
    - glob2==0.7
    - h5py==3.8.0
    - imageio==2.28.1
    - imageio-ffmpeg==0.4.8
    - ipdb==0.13.13
    - ipympl==0.9.3
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.1
    - jinja2==3.1.3
    - jupyterlab-widgets
    - lazy-loader==0.3
    - markupsafe==2.1.3
    - mat73==0.60
    - mne==1.6.0
    - moviepy==1.0.3
    - multiprocess==0.70.14
    - neo==0.12.0
    - pandas
    - patsy==0.5.3
    - pooch==1.8.0
    - proglog==0.1.10
    - pyasn1==0.5.0
    - pybind11==2.11.1
    - pygments==2.11.2
    - pyqt5-sip==12.11.0
    - pysmb==1.2.9.1
    - pyzmq==23.2.0
    - quantities==0.14.1
    - requests==2.28.2
    - scipy
    - seaborn
    - soupsieve==2.4
    - statsmodels==0.13.5
    - tomli==2.0.1
    - tqdm
    - urllib3==1.26.15
    - wave==0.0.2
    - wheel==0.38.4
    - widgetsnbextension==4.0.9
